export const FUENTES_ATLAS_CEREBRAL = [
  {
    id: "terminologia-neuroanatomica",
    recurso: "Terminologia Neuroanatomica / Terminologia Anatomica",
    uso: "Nomenclatura y jerarquia anatomica de referencia.",
    licencia: "Referencia academica; no se integra geometria externa.",
    fechaConsulta: "2026-07-12"
  },
  {
    id: "fase1-procedural",
    recurso: "Geometria procedural educativa COGNICION Labs",
    uso: "Prototipo fase 1 sin modelo GLB externo; cada estructura es seleccionable y reemplazable por nodos GLB futuros.",
    licencia: "Propia del proyecto; no deriva de modelos protegidos.",
    fechaConsulta: "2026-07-12"
  }
];

export const NIVELES_ATLAS_CEREBRAL = [
  { id: "superficie", nombre: "Superficie cortical" },
  { id: "surcos", nombre: "Surcos y circunvoluciones" },
  { id: "lobulos", nombre: "Lobulos" },
  { id: "areas", nombre: "Areas corticales" },
  { id: "sustancia-blanca", nombre: "Sustancia blanca" },
  { id: "tractos", nombre: "Tractos" },
  { id: "nucleos", nombre: "Nucleos profundos" },
  { id: "limbico", nombre: "Sistema limbico" },
  { id: "hipocampo", nombre: "Hipocampo" },
  { id: "amigdala", nombre: "Amigdala" },
  { id: "ventriculos", nombre: "Ventriculos" },
  { id: "vasculatura", nombre: "Vasculatura" },
  { id: "cerebelo", nombre: "Cerebelo y tronco" },
  { id: "clinico", nombre: "Relaciones clinicas" },
  { id: "micro", nombre: "Vista microscopica educativa" }
];

export const ESTRUCTURAS_ATLAS_CEREBRAL = [
  {
    id: "brain",
    name_es: "Cerebro",
    name_en: "Brain",
    name_la: "Encephalon",
    parent_id: null,
    hemisphere: "bilateral",
    system: "sistema nervioso central",
    category: "root",
    model_node: "BRAIN_ROOT",
    levels: ["superficie"],
    description: "Representacion educativa del encefalo humano para exploracion anatomica. Fase 1 prioriza lobulo temporal izquierdo.",
    boundaries: ["Calota y base craneal no modeladas en esta fase"],
    relations: ["Hemisferios, cerebelo y tronco encefalico"],
    functions: ["Integracion sensorial, motora, cognitiva y afectiva"],
    clinical_relevance: ["Atlas docente, no diagnostico"],
    confidence_level: "medio",
    detail_level: "fase 1 macroscopia"
  },
  {
    id: "left-hemisphere",
    name_es: "Hemisferio cerebral izquierdo",
    name_en: "Left cerebral hemisphere",
    name_la: "Hemispherium cerebri sinistrum",
    parent_id: "brain",
    hemisphere: "left",
    system: "corteza cerebral",
    category: "hemisphere",
    model_node: "L_HEMISPHERE",
    levels: ["superficie", "lobulos"],
    description: "Hemisferio izquierdo con superficie cortical educativa y fisura longitudinal visible.",
    boundaries: ["Separado del derecho por fisura longitudinal"],
    relations: ["Cuerpo calloso medial", "Lobulo temporal lateral e inferior"],
    functions: ["Procesamiento lateralizado variable; lenguaje usualmente dominante en muchos diestros"],
    clinical_relevance: ["Lesiones temporales posteriores dominantes pueden alterar comprension verbal"],
    confidence_level: "medio",
    detail_level: "macroscopia educativa"
  },
  {
    id: "right-hemisphere",
    name_es: "Hemisferio cerebral derecho",
    name_en: "Right cerebral hemisphere",
    name_la: "Hemispherium cerebri dextrum",
    parent_id: "brain",
    hemisphere: "right",
    system: "corteza cerebral",
    category: "hemisphere",
    model_node: "R_HEMISPHERE",
    levels: ["superficie", "lobulos"],
    description: "Hemisferio derecho implementado como referencia global; detalle temporal derecho se ampliara en fase posterior.",
    boundaries: ["Fisura longitudinal medial"],
    relations: ["Cuerpo calloso", "Hemisferio izquierdo"],
    functions: ["Procesamiento visuoespacial y social, con variabilidad individual"],
    clinical_relevance: ["Modelo de referencia; no segmentacion individual"],
    confidence_level: "medio",
    detail_level: "referencia global"
  },
  {
    id: "corpus-callosum",
    name_es: "Cuerpo calloso",
    name_en: "Corpus callosum",
    name_la: "Corpus callosum",
    parent_id: "brain",
    hemisphere: "midline",
    system: "sustancia blanca",
    category: "commissure",
    model_node: "CORPUS_CALLOSUM",
    levels: ["sustancia-blanca", "tractos"],
    description: "Principal comisura interhemisferica. Se muestra como banda medial arqueada.",
    boundaries: ["Rostrum, genu, cuerpo y esplenio no seccionados aun en subnodos"],
    relations: ["Ventriculos laterales", "Corteza medial"],
    functions: ["Conexion interhemisferica"],
    clinical_relevance: ["Lesiones pueden producir sindromes de desconexion"],
    confidence_level: "medio",
    detail_level: "macroscopia simplificada"
  },
  {
    id: "left-temporal-lobe",
    name_es: "Lobulo temporal izquierdo",
    name_en: "Left temporal lobe",
    name_la: "Lobus temporalis sinister",
    parent_id: "left-hemisphere",
    hemisphere: "left",
    system: "corteza cerebral",
    category: "lobe",
    model_node: "L_TEMPORAL_LOBE",
    levels: ["lobulos", "superficie"],
    description: "Region lateral, inferior y medial del hemisferio izquierdo, delimitada superiormente por la cisura lateral y posteriormente por transiciones temporooccipital/parietal variables.",
    boundaries: ["Cisura lateral superior", "Polo temporal anterior", "Transicion temporooccipital posterior variable"],
    relations: ["Insula profunda", "Lobulo frontal", "Lobulo parietal", "Hipocampo y amigdala mediales"],
    blood_supply: ["Ramas temporales de arteria cerebral media", "Ramas temporales de arteria cerebral posterior"],
    functions: ["Audicion", "lenguaje receptivo en hemisferio dominante", "memoria", "reconocimiento de objetos y rostros", "integracion emocional"],
    clinical_relevance: ["Epilepsia temporal", "afasia receptiva dominante", "alteraciones de memoria", "hemianopsia por asa de Meyer"],
    confidence_level: "alto para jerarquia; medio para geometria procedural",
    detail_level: "fase 1 prioritaria"
  },
  {
    id: "left-superior-temporal-gyrus",
    name_es: "Giro temporal superior izquierdo",
    name_en: "Left superior temporal gyrus",
    name_la: "Gyrus temporalis superior sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "corteza cerebral",
    category: "gyrus",
    model_node: "L_STG",
    levels: ["surcos", "areas"],
    description: "Giro lateral superior del lobulo temporal, relacionado con procesamiento auditivo y lenguaje posterior en regiones dominantes.",
    boundaries: ["Cisura lateral superior", "Surco temporal superior inferior"],
    relations: ["Planum temporale", "region temporal posterior", "union temporoparietal"],
    functions: ["Procesamiento auditivo", "comprension verbal en porciones posteriores dominantes"],
    clinical_relevance: ["Lesion posterior dominante puede relacionarse con alteraciones de comprension"],
    confidence_level: "medio",
    detail_level: "macroscopia fase 1"
  },
  {
    id: "left-middle-temporal-gyrus",
    name_es: "Giro temporal medio izquierdo",
    name_en: "Left middle temporal gyrus",
    name_la: "Gyrus temporalis medius sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "corteza cerebral",
    category: "gyrus",
    model_node: "L_MTG",
    levels: ["surcos", "areas"],
    description: "Giro lateral intermedio, asociado con procesamiento semantico y asociaciones temporales.",
    boundaries: ["Surco temporal superior", "Surco temporal inferior"],
    relations: ["Giros temporal superior e inferior"],
    functions: ["Procesamiento semantico", "integracion auditivo-visual"],
    clinical_relevance: ["Compromiso en redes de lenguaje y demencia semantica segun distribucion"],
    confidence_level: "medio",
    detail_level: "macroscopia fase 1"
  },
  {
    id: "left-inferior-temporal-gyrus",
    name_es: "Giro temporal inferior izquierdo",
    name_en: "Left inferior temporal gyrus",
    name_la: "Gyrus temporalis inferior sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "corteza cerebral",
    category: "gyrus",
    model_node: "L_ITG",
    levels: ["surcos", "areas"],
    description: "Giro lateral inferior, en transicion hacia superficie basal temporal.",
    boundaries: ["Surco temporal inferior", "borde inferolateral temporal"],
    relations: ["Giro fusiforme", "corteza inferotemporal"],
    functions: ["Reconocimiento visual complejo", "procesamiento de objetos"],
    clinical_relevance: ["Lesiones ventrales pueden alterar reconocimiento visual"],
    confidence_level: "medio",
    detail_level: "macroscopia fase 1"
  },
  {
    id: "left-superior-temporal-sulcus",
    name_es: "Surco temporal superior izquierdo",
    name_en: "Left superior temporal sulcus",
    name_la: "Sulcus temporalis superior sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "surcos corticales",
    category: "sulcus",
    model_node: "L_STS",
    levels: ["surcos"],
    description: "Surco entre giros temporal superior y medio. Sus limites y continuidad muestran variabilidad interindividual.",
    boundaries: ["Giro temporal superior arriba", "giro temporal medio abajo"],
    relations: ["Redes de percepcion social y audio-visual"],
    functions: ["Integracion auditivo-visual y social en regiones posteriores"],
    clinical_relevance: ["Area de interes en cognicion social y lenguaje"],
    confidence_level: "medio",
    detail_level: "surco representado por depresion/linea educativa"
  },
  {
    id: "left-inferior-temporal-sulcus",
    name_es: "Surco temporal inferior izquierdo",
    name_en: "Left inferior temporal sulcus",
    name_la: "Sulcus temporalis inferior sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "surcos corticales",
    category: "sulcus",
    model_node: "L_ITS",
    levels: ["surcos"],
    description: "Surco lateral inferior entre giro temporal medio e inferior; su continuidad puede variar.",
    boundaries: ["Giro temporal medio", "giro temporal inferior"],
    relations: ["Corteza inferotemporal"],
    functions: ["Referencia anatomica para superficie lateral temporal"],
    clinical_relevance: ["Util en localizacion de lesiones temporales"],
    confidence_level: "medio",
    detail_level: "surco educativo"
  },
  {
    id: "left-temporal-pole",
    name_es: "Polo temporal izquierdo",
    name_en: "Left temporal pole",
    name_la: "Polus temporalis sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "corteza temporal",
    category: "pole",
    model_node: "L_TEMPORAL_POLE",
    levels: ["lobulos", "areas"],
    description: "Porcion anterior del lobulo temporal, relacionada con integracion semantica, social y limbica.",
    boundaries: ["Extremo anterior temporal"],
    relations: ["Amigdala", "uncus", "corteza orbitofrontal por fasciculo uncinado"],
    functions: ["Memoria semantica", "asociacion social-emocional"],
    clinical_relevance: ["Atrofia anterior temporal puede verse en demencia semantica"],
    confidence_level: "medio",
    detail_level: "macroscopia fase 1"
  },
  {
    id: "left-heschl-gyrus",
    name_es: "Giros temporales transversos de Heschl izquierdos",
    name_en: "Left transverse temporal gyri of Heschl",
    name_la: "Gyri temporales transversi sinistri",
    parent_id: "left-superior-temporal-gyrus",
    hemisphere: "left",
    system: "corteza auditiva",
    category: "gyrus",
    model_node: "L_HESCHL",
    levels: ["areas", "surcos"],
    description: "Region del plano supratemporal que contiene corteza auditiva primaria. Numero y morfologia de giros de Heschl son variables.",
    boundaries: ["Plano temporal supratemporal", "cercano a planum temporale y planum polare"],
    functions: ["Procesamiento auditivo primario"],
    clinical_relevance: ["Referencia en neuroimagen funcional auditiva"],
    confidence_level: "medio",
    detail_level: "representacion esquematica seleccionable"
  },
  {
    id: "left-planum-temporale",
    name_es: "Planum temporale izquierdo",
    name_en: "Left planum temporale",
    name_la: "Planum temporale sinistrum",
    parent_id: "left-superior-temporal-gyrus",
    hemisphere: "left",
    system: "corteza auditiva/lenguaje",
    category: "cortical area",
    model_node: "L_PLANUM_TEMPORALE",
    levels: ["areas"],
    description: "Region posterior al giro de Heschl en la superficie supratemporal; asimetria izquierda frecuente, relacionada con redes de lenguaje.",
    boundaries: ["Posterior a Heschl; limites macroscópicos variables"],
    functions: ["Procesamiento auditivo complejo", "lenguaje"],
    clinical_relevance: ["Variabilidad anatomica relevante en estudios de lenguaje"],
    confidence_level: "medio",
    detail_level: "area aproximada"
  },
  {
    id: "left-fusiform-gyrus",
    name_es: "Giro fusiforme izquierdo",
    name_en: "Left fusiform gyrus",
    name_la: "Gyrus fusiformis sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "corteza temporal basal",
    category: "gyrus",
    model_node: "L_FUSIFORM",
    levels: ["surcos", "areas"],
    description: "Giro occipitotemporal medial/lateral de superficie basal, asociado a reconocimiento visual complejo.",
    boundaries: ["Surco colateral medial", "surco occipitotemporal lateral"],
    relations: ["Giro parahipocampal", "corteza inferotemporal"],
    functions: ["Reconocimiento visual de objetos y rostros en redes bilaterales"],
    clinical_relevance: ["Lesiones ventrales pueden contribuir a agnosias visuales"],
    confidence_level: "medio",
    detail_level: "superficie basal fase 1"
  },
  {
    id: "left-collateral-sulcus",
    name_es: "Surco colateral izquierdo",
    name_en: "Left collateral sulcus",
    name_la: "Sulcus collateralis sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "surcos corticales",
    category: "sulcus",
    model_node: "L_COLLATERAL_SULCUS",
    levels: ["surcos"],
    description: "Surco basal que separa giro fusiforme de giro parahipocampal en gran parte de su trayecto.",
    boundaries: ["Giro fusiforme lateral", "giro parahipocampal medial"],
    functions: ["Referencia anatomica basal"],
    clinical_relevance: ["Util para localizar corteza entorrinal y parahipocampal en neuroimagen"],
    confidence_level: "medio",
    detail_level: "surco educativo"
  },
  {
    id: "left-parahippocampal-gyrus",
    name_es: "Giro parahipocampal izquierdo",
    name_en: "Left parahippocampal gyrus",
    name_la: "Gyrus parahippocampalis sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "sistema limbico",
    category: "gyrus",
    model_node: "L_PARAHIPPOCAMPAL_GYRUS",
    levels: ["limbico", "hipocampo"],
    description: "Giro medial temporal que rodea la formacion hipocampal y participa en memoria contextual y espacial.",
    boundaries: ["Surco colateral lateral", "surco hipocampal medial"],
    relations: ["Uncus", "corteza entorrinal", "hipocampo"],
    functions: ["Memoria contextual", "navegacion espacial", "conexion neocorteza-hipocampo"],
    clinical_relevance: ["Compromiso temporomedial en epilepsia y enfermedad de Alzheimer"],
    confidence_level: "medio",
    detail_level: "medial/basal fase 1"
  },
  {
    id: "left-uncus",
    name_es: "Uncus izquierdo",
    name_en: "Left uncus",
    name_la: "Uncus sinister",
    parent_id: "left-parahippocampal-gyrus",
    hemisphere: "left",
    system: "sistema limbico",
    category: "cortex",
    model_node: "L_UNCUS",
    levels: ["limbico", "amigdala"],
    description: "Porcion anteromedial del giro parahipocampal, vecina a amigdala e hipocampo anterior.",
    boundaries: ["Polo temporal medial", "amigdala profunda"],
    relations: ["Mesencefalo", "tentorio", "amigdala", "hipocampo"],
    functions: ["Olfaccion y redes limbicas"],
    clinical_relevance: ["Herniacion uncal puede comprimir estructuras del tronco; representacion solo educativa"],
    confidence_level: "medio",
    detail_level: "medial fase 1"
  },
  {
    id: "left-hippocampus",
    name_es: "Hipocampo izquierdo",
    name_en: "Left hippocampus",
    name_la: "Hippocampus sinister",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "formacion hipocampal",
    category: "limbic structure",
    model_node: "L_HIPPOCAMPUS",
    levels: ["hipocampo", "limbico"],
    description: "Estructura temporomedial relacionada con memoria declarativa. En fase 1 se representa con cabeza, cuerpo y cola de forma simplificada.",
    boundaries: ["Piso del asta temporal del ventriculo lateral", "giro parahipocampal inferior"],
    relations: ["Fimbria", "fornix", "asta temporal", "amigdala anterior"],
    afferents: ["Corteza entorrinal por via perforante"],
    efferents: ["Subiculo", "fornix"],
    functions: ["Consolidacion de memoria declarativa", "navegacion espacial"],
    clinical_relevance: ["Esclerosis mesial temporal", "Alzheimer temporomedial", "amnesia"],
    confidence_level: "medio",
    detail_level: "subdivision macroscopica inicial"
  },
  {
    id: "left-amygdala",
    name_es: "Amigdala izquierda",
    name_en: "Left amygdala",
    name_la: "Corpus amygdaloideum sinistrum",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "sistema limbico",
    category: "nucleus complex",
    model_node: "L_AMYGDALA",
    levels: ["amigdala", "limbico", "nucleos"],
    description: "Complejo nuclear anteromedial temporal relacionado con procesamiento emocional y saliencia. Subnucleos se agregaran en fase 2.",
    boundaries: ["Anterior al hipocampo", "profundo al uncus"],
    relations: ["Asta temporal", "uncus", "hipocampo anterior", "estria terminal"],
    functions: ["Saliencia emocional", "aprendizaje asociativo aversivo", "modulacion de memoria"],
    clinical_relevance: ["Epilepsia temporal", "Kluver-Bucy en lesiones bilaterales extensas", "encefalitis limbica"],
    confidence_level: "medio",
    detail_level: "complejo inicial"
  },
  {
    id: "left-temporal-horn",
    name_es: "Asta temporal del ventriculo lateral izquierdo",
    name_en: "Left temporal horn of lateral ventricle",
    name_la: "Cornu temporale ventriculi lateralis sinistri",
    parent_id: "brain",
    hemisphere: "left",
    system: "ventriculos",
    category: "ventricle",
    model_node: "L_TEMPORAL_HORN",
    levels: ["ventriculos"],
    description: "Extension temporal del ventriculo lateral, relacionada con hipocampo en su piso y amigdala anteriormente.",
    boundaries: ["Piso hipocampal", "techo con cola del caudado y tapetum"],
    relations: ["Hipocampo", "amigdala", "plexo coroideo"],
    functions: ["Circulacion de LCR"],
    clinical_relevance: ["Dilatacion puede acompanar atrofia temporomedial"],
    confidence_level: "medio",
    detail_level: "volumen simplificado"
  },
  {
    id: "left-meyer-loop",
    name_es: "Asa de Meyer izquierda",
    name_en: "Left Meyer loop",
    name_la: "Radiatio optica pars temporalis sinistra",
    parent_id: "left-temporal-lobe",
    hemisphere: "left",
    system: "sustancia blanca",
    category: "tract",
    model_node: "L_MEYER_LOOP",
    levels: ["tractos"],
    description: "Porcion anterior temporal de la radiacion optica. Se muestra como tracto simplificado educativo.",
    boundaries: ["Trayecto temporal anterior variable"],
    relations: ["Asta temporal", "cuerpo geniculado lateral", "corteza occipital"],
    functions: ["Transmision visual hacia corteza occipital"],
    clinical_relevance: ["Lesion puede causar cuadrantanopsia superior contralateral"],
    confidence_level: "bajo-medio por variabilidad anatómica",
    detail_level: "tracto esquematico"
  },
  {
    id: "left-arcuate-fasciculus",
    name_es: "Fasciculo arqueado izquierdo",
    name_en: "Left arcuate fasciculus",
    name_la: "Fasciculus arcuatus sinister",
    parent_id: "left-hemisphere",
    hemisphere: "left",
    system: "sustancia blanca",
    category: "tract",
    model_node: "L_ARCUATE",
    levels: ["tractos"],
    description: "Tracto frontotemporal/parietal simplificado, relevante para redes del lenguaje. La anatomia real es compleja y variable.",
    relations: ["Region temporal posterior", "regiones frontales del lenguaje"],
    functions: ["Conectividad dorsal del lenguaje"],
    clinical_relevance: ["Lesiones pueden contribuir a afasias de conduccion"],
    confidence_level: "bajo-medio por representacion esquematica",
    detail_level: "tracto fase 1"
  },
  {
    id: "thalamus",
    name_es: "Talamo",
    name_en: "Thalamus",
    name_la: "Thalamus",
    parent_id: "brain",
    hemisphere: "bilateral",
    system: "nucleos profundos",
    category: "deep nuclei",
    model_node: "THALAMUS",
    levels: ["nucleos"],
    description: "Nucleo diencefalico de relevo e integracion. En fase 1 se representa como volumen bilateral simplificado.",
    relations: ["Capsula interna", "ventriculo lateral/tercer ventriculo", "cuerpos geniculados"],
    functions: ["Relevo sensorial y motor", "redes atencionales"],
    clinical_relevance: ["Lesiones talamicas producen sindromes sensitivos, cognitivos o de conciencia segun nucleo"],
    confidence_level: "medio",
    detail_level: "volumen global"
  },
  {
    id: "cerebellum",
    name_es: "Cerebelo",
    name_en: "Cerebellum",
    name_la: "Cerebellum",
    parent_id: "brain",
    hemisphere: "bilateral",
    system: "cerebelo",
    category: "hindbrain",
    model_node: "CEREBELLUM",
    levels: ["cerebelo"],
    description: "Estructura infratentorial para coordinacion motora y funciones cognitivas afectivas. Fase 1: referencia global.",
    relations: ["Tronco encefalico", "fosa posterior"],
    functions: ["Coordinacion", "aprendizaje motor", "modulacion cognitivo-afectiva"],
    clinical_relevance: ["Ataxia, dismetria y sindromes cerebelosos"],
    confidence_level: "medio",
    detail_level: "referencia global"
  },
  {
    id: "brainstem",
    name_es: "Tronco encefalico",
    name_en: "Brainstem",
    name_la: "Truncus encephali",
    parent_id: "brain",
    hemisphere: "midline",
    system: "tronco encefalico",
    category: "brainstem",
    model_node: "BRAINSTEM",
    levels: ["cerebelo"],
    description: "Mesencefalo, puente y bulbo representados de forma global en fase 1.",
    relations: ["Talamo superior", "cerebelo posterior", "medula espinal inferior"],
    functions: ["Conduccion de vias", "nucleos de pares craneales", "control autonomico"],
    clinical_relevance: ["Lesiones pueden ser neurologicamente criticas"],
    confidence_level: "medio",
    detail_level: "referencia global"
  }
];

export const COMPLETITUD_ATLAS_CEREBRAL = {
  planificadas: 120,
  implementadas: ESTRUCTURAS_ATLAS_CEREBRAL.length,
  conGeometria: ESTRUCTURAS_ATLAS_CEREBRAL.length - 1,
  fichaCompleta: 16,
  pendientes: [
    "Subnucleos amigdalinos detallados",
    "Capas CA1-CA4 y giro dentado en geometria microscopica",
    "Vasculatura temporal completa",
    "Modelo GLB/segmentacion anatomica con licencia compatible",
    "Lobulo temporal derecho con mismo nivel de detalle"
  ],
  regiones: {
    "Lobulo temporal izquierdo": {
      macroscopia: 68,
      nucleos: 35,
      tractos: 28,
      vasculatura: 0,
      clinica: 45,
      validacion: "en revision"
    }
  }
};
