export const EXPERIMENTOS_NEUROFISIOLOGIA = [
  { id: "reposo_k", titulo: "¿Por que el potencial de reposo se aproxima al potasio?", objetivo: "Observar como la alta permeabilidad al K+ desplaza Vm hacia EK.", hipotesis: "Si PK aumenta, Vm se acercara a EK.", variableIndependiente: "Permeabilidad al K+", variableDependiente: "Potencial de membrana", parametros: { preset: "permeableK" }, pasos: ["Carga el preset.", "Compara EK con Vm.", "Aumenta y disminuye PK."], preguntas: ["¿Que ion domina el reposo?", "¿Por que Cl- se invierte en GHK?"], resultadoEsperado: "Vm se aproxima a EK cuando PK domina.", explicacion: "La ecuacion GHK pondera concentraciones por permeabilidad; en reposo PK suele dominar." },
  { id: "k_extra", titulo: "Efecto de aumentar el potasio extracelular", objetivo: "Explorar despolarizacion por hiperpotasemia.", hipotesis: "Aumentar K+ extracelular hara menos negativo EK y Vm.", variableIndependiente: "K+ extracelular", variableDependiente: "Vm y EK", parametros: { preset: "hiperpotasemia" }, pasos: ["Carga hiperpotasemia.", "Observa EK y Vm.", "Compara con fisiologico."], preguntas: ["¿Vm se despolariza?"], resultadoEsperado: "Vm se hace menos negativo.", explicacion: "Disminuye el gradiente quimico de salida del K+." },
  { id: "na_bajo", titulo: "Efecto de disminuir el sodio extracelular", objetivo: "Observar menor fuerza impulsora para Na+.", hipotesis: "Menor Na+ extracelular reduce ENa y puede disminuir amplitud del potencial.", variableIndependiente: "Na+ extracelular", variableDependiente: "ENa / pico", parametros: { preset: "hiponatremia" }, pasos: ["Carga hiponatremia.", "Observa ENa.", "Aplica estimulo en potencial de accion."], preguntas: ["¿El pico teorico baja?"], resultadoEsperado: "ENa disminuye.", explicacion: "El gradiente electroquimico de Na+ se reduce." },
  { id: "bloqueo_na", titulo: "Bloqueo de canales de sodio", objetivo: "Reducir gNa y observar fallo o menor pico.", hipotesis: "Menor gNa reduce la fase ascendente.", variableIndependiente: "Conductancia/permeabilidad al Na+", variableDependiente: "Generacion del PA", parametros: { preset: "bloqueoNa", gNa: 25 }, pasos: ["Carga bloqueo Na+.", "Aplica estimulo.", "Compara con control."], preguntas: ["¿Se alcanza el umbral?"], resultadoEsperado: "Puede fallar el potencial o tener menor amplitud.", explicacion: "La despolarizacion rapida depende de entrada de Na+." },
  { id: "bloqueo_k", titulo: "Bloqueo de canales de potasio", objetivo: "Observar repolarizacion lenta.", hipotesis: "Reducir K+ prolonga la repolarizacion.", variableIndependiente: "Conductancia K+", variableDependiente: "Repolarizacion", parametros: { preset: "bloqueoK", gK: 8 }, pasos: ["Carga bloqueo K+.", "Aplica estimulo.", "Observa repolarizacion."], preguntas: ["¿Aumenta la duracion?"], resultadoEsperado: "Repolarizacion mas lenta.", explicacion: "La salida de K+ ayuda a repolarizar." },
  { id: "refractario", titulo: "Periodo refractario absoluto y relativo", objetivo: "Aplicar un segundo estimulo en distintos intervalos.", hipotesis: "Durante inactivacion de Na+ no habra segundo PA.", variableIndependiente: "Separacion entre estimulos", variableDependiente: "Segundo PA", parametros: { segundoEstimulo: true }, pasos: ["Activa segundo estimulo.", "Prueba separacion corta.", "Aumenta la separacion."], preguntas: ["¿Cuando reaparece respuesta?"], resultadoEsperado: "Falla en absoluto; puede reaparecer en relativo con mayor intensidad.", explicacion: "Canales de Na+ inactivados limitan excitabilidad." },
  { id: "saltatoria", titulo: "Conduccion continua frente a saltatoria", objetivo: "Comparar mielinizado y amielinico.", hipotesis: "La mielina aumenta velocidad.", variableIndependiente: "Mielina", variableDependiente: "Velocidad", parametros: { mielina: true }, pasos: ["Simula con mielina.", "Desactiva mielina.", "Compara velocidad."], preguntas: ["¿Cual es mas rapido?"], resultadoEsperado: "Mielinizado conduce mas rapido.", explicacion: "Mielina reduce capacitancia efectiva y concentra canales en nodos." },
  { id: "diametro", titulo: "Efecto del diametro axonal", objetivo: "Aumentar diametro y comparar velocidad.", hipotesis: "Mayor diametro aumenta conduccion.", variableIndependiente: "Diametro", variableDependiente: "Velocidad", parametros: { diametroUm: 5 }, pasos: ["Aumenta diametro.", "Reduce diametro.", "Compara."], preguntas: ["¿Como cambia la resistencia axial?"], resultadoEsperado: "Mayor diametro incrementa velocidad.", explicacion: "Disminuye resistencia axial relativa." },
  { id: "temperatura", titulo: "Efecto de la temperatura", objetivo: "Explorar cambios de velocidad por temperatura.", hipotesis: "Temperatura moderadamente mayor acelera cinetica.", variableIndependiente: "Temperatura", variableDependiente: "Velocidad / cinetica", parametros: { temperaturaC: 32 }, pasos: ["Baja temperatura.", "Sube temperatura.", "Compara velocidad."], preguntas: ["¿Que ocurre con frio?"], resultadoEsperado: "Frio reduce velocidad.", explicacion: "La cinetica de canales y conduccion depende de temperatura." },
  { id: "desmielinizacion", titulo: "Desmielinizacion focal", objetivo: "Observar menor seguridad y velocidad.", hipotesis: "Una lesion desmielinizante reduce velocidad y amplitud distal.", variableIndependiente: "Severidad de desmielinizacion", variableDependiente: "Velocidad / amplitud", parametros: { desmielinizacion: true }, pasos: ["Activa lesion.", "Ajusta severidad.", "Observa electrodos distales."], preguntas: ["¿Hay mayor retraso?"], resultadoEsperado: "Reduce velocidad y seguridad de conduccion.", explicacion: "La perdida de mielina aumenta capacitancia y fuga de corriente." }
];