const { CLINICAL_EVIDENCE_REGISTRY_VERSION } = require("./config");

const CLINICAL_EVIDENCE_REGISTRY = Object.freeze([
  {
    evidenceId: "tripod-ai",
    title: "TRIPOD+AI statement: updated guidance for reporting clinical prediction models that use regression or machine learning methods",
    titleEs: "Declaración TRIPOD+AI: guía actualizada para reportar modelos de predicción clínica con regresión o aprendizaje automático",
    authors: "Collins GS et al.",
    year: 2024,
    journal: "BMJ",
    doi: "10.1136/bmj-2023-078378",
    url: "https://www.bmj.com/content/385/bmj-2023-078378",
    evidenceType: "reporting_guideline",
    domain: "prediction_model_reporting",
    variablesSupported: [],
    modelSupported: ["future_predictive_models"],
    notes: "Marco de transparencia y reporte; no valida resultados de COGNICIÓN.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "probast-ai",
    title: "PROBAST+AI: an updated quality, risk of bias, and applicability assessment tool for prediction models using regression or artificial intelligence methods",
    titleEs: "PROBAST+AI: herramienta actualizada para evaluar calidad, riesgo de sesgo y aplicabilidad de modelos predictivos",
    authors: "Moons KGM et al.",
    year: 2025,
    journal: "BMJ",
    doi: "10.1136/bmj-2024-082505",
    url: "https://www.bmj.com/content/388/bmj-2024-082505",
    evidenceType: "risk_of_bias_framework",
    domain: "model_quality",
    variablesSupported: [],
    modelSupported: ["future_predictive_models"],
    notes: "Marco para riesgo de sesgo y aplicabilidad; no es evidencia externa del producto.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "nice-esf",
    title: "Evidence standards framework for digital health technologies",
    titleEs: "Marco de estándares de evidencia para tecnologías de salud digital",
    authors: "National Institute for Health and Care Excellence",
    year: 2022,
    journal: "NICE Guidance ECD7",
    doi: "",
    url: "https://www.nice.org.uk/corporate/ecd7",
    evidenceType: "evidence_standard",
    domain: "digital_health_evidence",
    variablesSupported: [],
    modelSupported: ["evaluation_planning"],
    notes: "Estándar de evidencia para tecnologías digitales; no es validación automática.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "nice-rwe",
    title: "NICE real-world evidence framework",
    titleEs: "Marco NICE de evidencia del mundo real",
    authors: "National Institute for Health and Care Excellence",
    year: 2022,
    journal: "NICE Guidance ECD9",
    doi: "",
    url: "https://www.nice.org.uk/corporate/ecd9",
    evidenceType: "real_world_evidence_framework",
    domain: "real_world_data",
    variablesSupported: [],
    modelSupported: ["observational_analysis"],
    notes: "Marco para calidad y uso de datos del mundo real; no establece causalidad.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "fda-cds",
    title: "Clinical Decision Support Software",
    titleEs: "Software de apoyo a decisiones clínicas",
    authors: "U.S. Food and Drug Administration",
    year: null,
    journal: "FDA Guidance",
    doi: "",
    url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/clinical-decision-support-software",
    evidenceType: "regulatory_methodological_reference",
    domain: "clinical_decision_support",
    variablesSupported: [],
    modelSupported: ["support_tools"],
    notes: "Referencia regulatoria/metodológica; no es autorización ni validación del producto.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "nist-sematech-statistics-handbook",
    title: "NIST/SEMATECH e-Handbook of Statistical Methods",
    titleEs: "Manual electrónico NIST/SEMATECH de métodos estadísticos",
    authors: "National Institute of Standards and Technology",
    year: null,
    journal: "NIST",
    doi: "10.18434/M32189",
    url: "https://www.nist.gov/programs-projects/nistsematech-engineering-statistics-handbook",
    evidenceType: "statistical_methodology",
    domain: "association_measurement",
    variablesSupported: ["continuous", "ordinal"],
    modelSupported: ["pearson_correlation", "spearman_rank_correlation"],
    notes: "Referencia metodologica para medidas de asociacion; no convierte correlacion en causalidad.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "benjamini-hochberg-1995",
    title: "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing",
    titleEs: "Control de la tasa de falsos descubrimientos: un enfoque práctico para comparaciones múltiples",
    authors: "Benjamini Y, Hochberg Y",
    year: 1995,
    journal: "Journal of the Royal Statistical Society: Series B",
    doi: "10.1111/j.2517-6161.1995.tb02031.x",
    url: "https://doi.org/10.1111/j.2517-6161.1995.tb02031.x",
    evidenceType: "statistical_methodology",
    domain: "multiple_testing",
    variablesSupported: [],
    modelSupported: ["false_discovery_rate_control"],
    notes: "Se usa para ajustar valores p al explorar muchos pares; no valida por si solo una asociacion.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "asa-p-values-2016",
    title: "The ASA Statement on p-Values: Context, Process, and Purpose",
    titleEs: "Declaración de la ASA sobre valores p: contexto, proceso y propósito",
    authors: "Wasserstein RL, Lazar NA",
    year: 2016,
    journal: "The American Statistician",
    doi: "10.1080/00031305.2016.1154108",
    url: "https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf",
    evidenceType: "statistical_interpretation_guidance",
    domain: "statistical_interpretation",
    variablesSupported: [],
    modelSupported: ["association_interpretation", "multiple_testing_reporting"],
    notes: "Los valores p o q no miden la magnitud ni la importancia clínica y no deben sostener por sí solos una conclusión.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "stability-selection-2010",
    title: "Stability selection",
    titleEs: "Selección por estabilidad",
    authors: "Meinshausen N, Bühlmann P",
    year: 2010,
    journal: "Journal of the Royal Statistical Society: Series B",
    doi: "10.1111/j.1467-9868.2010.00740.x",
    url: "https://doi.org/10.1111/j.1467-9868.2010.00740.x",
    evidenceType: "statistical_methodology",
    domain: "robustness_assessment",
    variablesSupported: [],
    modelSupported: ["subsample_stability_screening"],
    notes: "Informa la comprobación de estabilidad entre submuestras. COGNICIÓN no afirma implementar las garantías formales completas del procedimiento original.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "closed-patterns-1999",
    title: "Discovering Frequent Closed Itemsets for Association Rules",
    titleEs: "Descubrimiento de conjuntos frecuentes cerrados para reglas de asociación",
    authors: "Pasquier N, Bastide Y, Taouil R, Lakhal L",
    year: 1999,
    journal: "International Conference on Database Theory",
    doi: "10.1007/3-540-49257-7_25",
    url: "https://doi.org/10.1007/3-540-49257-7_25",
    evidenceType: "pattern_mining_methodology",
    domain: "non_redundant_patterns",
    variablesSupported: [],
    modelSupported: ["closed_lexical_patterns"],
    notes: "Referencia para reducir patrones frecuentes redundantes; no aporta evidencia clínica externa.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "aha-ecg-standardization-part-i",
    title: "Recommendations for the Standardization and Interpretation of the Electrocardiogram: Part I: The Electrocardiogram and Its Technology",
    titleEs: "Recomendaciones para estandarización e interpretación del ECG, parte I: tecnología y medición",
    authors: "Kligfield P et al.",
    year: 2007,
    journal: "Journal of the American College of Cardiology",
    doi: "10.1016/j.jacc.2007.01.024",
    url: "https://pubmed.ncbi.nlm.nih.gov/17349896/",
    evidenceType: "clinical_measurement_standard",
    domain: "electrocardiography",
    variablesSupported: ["heart_rate", "pr_interval", "qrs_duration", "qt_interval"],
    modelSupported: ["ecg_contextual_interpretation"],
    notes: "Estandariza adquisición y medición. La interpretación computarizada requiere revisión médica del trazado original.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "aha-ecg-standardization-part-iii",
    title: "AHA/ACCF/HRS Recommendations for the Standardization and Interpretation of the Electrocardiogram: Part III: Intraventricular Conduction Disturbances",
    titleEs: "Recomendaciones para estandarización e interpretación del ECG, parte III: trastornos de conducción intraventricular",
    authors: "Surawicz B et al.",
    year: 2009,
    journal: "Circulation",
    doi: "10.1161/CIRCULATIONAHA.108.191095",
    url: "https://pubmed.ncbi.nlm.nih.gov/19228822/",
    evidenceType: "clinical_interpretation_standard",
    domain: "electrocardiography",
    variablesSupported: ["qrs_duration", "qrs_axis"],
    modelSupported: ["ecg_contextual_interpretation"],
    notes: "La duración QRS aislada no permite clasificar un bloqueo sin morfología de las derivaciones.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "aha-ecg-standardization-part-iv",
    title: "AHA/ACCF/HRS Recommendations for the Standardization and Interpretation of the Electrocardiogram: Part IV: The ST Segment, T and U Waves, and the QT Interval",
    titleEs: "Recomendaciones para estandarización e interpretación del ECG, parte IV: ST, T, U y QT",
    authors: "Rautaharju PM et al.",
    year: 2009,
    journal: "Circulation",
    doi: "10.1161/CIRCULATIONAHA.108.191096",
    url: "https://pubmed.ncbi.nlm.nih.gov/19228821/",
    evidenceType: "clinical_interpretation_standard",
    domain: "electrocardiography",
    variablesSupported: ["qt_interval", "qtc"],
    modelSupported: ["qtc_contextual_interpretation"],
    notes: "Informa medición y límites del QT/QTc; un umbral aislado no equivale a diagnóstico ni probabilidad individual.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "aha-torsade-prevention",
    title: "Prevention of Torsade de Pointes in Hospital Settings",
    titleEs: "Prevención de torsade de pointes en el entorno hospitalario",
    authors: "Drew BJ et al.",
    year: 2010,
    journal: "Circulation",
    doi: "10.1161/CIRCULATIONAHA.109.192704",
    url: "https://pubmed.ncbi.nlm.nih.gov/20142454/",
    evidenceType: "clinical_safety_statement",
    domain: "electrocardiography_qt_safety",
    variablesSupported: ["qtc", "potassium", "magnesium", "calcium", "heart_rate", "medications"],
    modelSupported: ["qtc_contextual_interpretation"],
    notes: "Describe factores de susceptibilidad a torsade. COGNICIÓN los presenta como contexto y no como decisión automática.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "aha-drug-induced-arrhythmias",
    title: "Drug-Induced Arrhythmias: A Scientific Statement From the American Heart Association",
    titleEs: "Arritmias inducidas por medicamentos: declaración científica de la AHA",
    authors: "Tisdale JE et al.",
    year: 2020,
    journal: "Circulation",
    doi: "10.1161/CIR.0000000000000905",
    url: "https://pubmed.ncbi.nlm.nih.gov/32929996/",
    evidenceType: "clinical_safety_statement",
    domain: "drug_induced_arrhythmias",
    variablesSupported: ["medications", "qtc", "rhythm", "heart_rate", "conduction"],
    modelSupported: ["medication_ecg_context"],
    notes: "Marco para revisar posibles efectos arrítmicos farmacológicos; no autoriza atribución causal automática ni suspensión de tratamiento.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  },
  {
    evidenceId: "fda-ich-e14-s7b",
    title: "E14 and S7B Clinical and Nonclinical Evaluation of QT/QTc Interval Prolongation and Proarrhythmic Potential — Questions and Answers",
    titleEs: "Evaluación clínica y no clínica de prolongación QT/QTc y potencial proarrítmico",
    authors: "U.S. Food and Drug Administration / International Council for Harmonisation",
    year: 2022,
    journal: "FDA Guidance for Industry",
    doi: "",
    url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/e14-and-s7b-clinical-and-nonclinical-evaluation-qtqtc-interval-prolongation-and-proarrhythmic",
    evidenceType: "regulatory_methodological_reference",
    domain: "drug_qt_methodology",
    variablesSupported: ["qt_interval", "qtc", "medications"],
    modelSupported: ["medication_ecg_context"],
    notes: "Referencia metodológica regulatoria para evaluación de efectos QT de fármacos; no valida automáticamente COGNICIÓN ni un resultado individual.",
    registryVersion: CLINICAL_EVIDENCE_REGISTRY_VERSION
  }
]);

function listClinicalEvidence() {
  return CLINICAL_EVIDENCE_REGISTRY.map((item) => ({ ...item }));
}

module.exports = { CLINICAL_EVIDENCE_REGISTRY, listClinicalEvidence };
