const crypto = require("node:crypto");
const { onCall, onRequest, HttpsError } = require("firebase-functions/v2/https");
const { defineSecret } = require("firebase-functions/params");
const admin = require("firebase-admin");

const GOOGLE_CLIENT_ID = defineSecret("GOOGLE_CLIENT_ID");
const GOOGLE_CLIENT_SECRET = defineSecret("GOOGLE_CLIENT_SECRET");
const GOOGLE_OAUTH_REDIRECT_URI = defineSecret("GOOGLE_OAUTH_REDIRECT_URI");
const GOOGLE_TOKEN_ENCRYPTION_KEY = defineSecret("GOOGLE_TOKEN_ENCRYPTION_KEY");
const db = admin.firestore();
const SCOPES = ["https://www.googleapis.com/auth/calendar.events", "https://www.googleapis.com/auth/calendar.calendarlist.readonly"];
const TIME_ZONE = "America/Mexico_City";
const STATE_TTL_MS = 10 * 60 * 1000;
const TOKEN_COLLECTION = "_googleCalendarTokens";

function secret(secretValue, fallbackName) { const value = secretValue?.value?.() || process.env[fallbackName] || ""; if (!value) throw new Error(`Secret ${fallbackName} no configurado`); return value; }
function redirectUri() { return secret(GOOGLE_OAUTH_REDIRECT_URI, "GOOGLE_OAUTH_REDIRECT_URI"); }
function keyBytes() { const raw = secret(GOOGLE_TOKEN_ENCRYPTION_KEY, "GOOGLE_TOKEN_ENCRYPTION_KEY"); const key = /^[0-9a-f]{64}$/i.test(raw) ? Buffer.from(raw, "hex") : Buffer.from(raw, "base64"); if (key.length !== 32) throw new Error("GOOGLE_TOKEN_ENCRYPTION_KEY debe ser una clave AES-256"); return key; }
function encrypt(value) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", keyBytes(), iv); const data = Buffer.concat([cipher.update(String(value || ""), "utf8"), cipher.final()]); return `${iv.toString("base64")}.${cipher.getAuthTag().toString("base64")}.${data.toString("base64")}`; }
function decrypt(value) { const [iv, tag, data] = String(value || "").split(".").map((part) => Buffer.from(part, "base64")); const decipher = crypto.createDecipheriv("aes-256-gcm", keyBytes(), iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(data), decipher.final()]).toString("utf8"); }
function requireAuth(request) { if (!request.auth?.uid) throw new HttpsError("unauthenticated", "Debes iniciar sesión."); return request.auth.uid; }
function safeId(value, label = "ID") { const id = String(value || "").trim(); if (!/^[A-Za-z0-9_:@.-]{1,256}$/.test(id)) throw new HttpsError("invalid-argument", `${label} inválido.`); return id; }
function normalizeError(error, fallback = "GOOGLE_TEMPORARILY_UNAVAILABLE") { const status = error?.status || error?.response?.status; if (status === 401) return { code: "GOOGLE_REAUTH_REQUIRED", userMessage: "Vuelve a conectar Google Calendar.", retryable: false }; if (status === 403) return { code: "GOOGLE_PERMISSION_DENIED", userMessage: "Google no concedió permisos suficientes.", retryable: false }; if (status === 404) return { code: "GOOGLE_EVENT_NOT_FOUND", userMessage: "El evento ya no existe en Google Calendar.", retryable: false }; if (status === 429) return { code: "GOOGLE_RATE_LIMITED", userMessage: "Google limitó temporalmente la operación.", retryable: true }; return { code: fallback, userMessage: "Google Calendar no está disponible temporalmente.", retryable: true }; }
async function googleFetch(path, options = {}) { const response = await fetch(`https://www.googleapis.com/calendar/v3${path}`, { ...options, headers: { "content-type": "application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(body?.error?.message || "Google Calendar API error"); error.status = response.status; error.body = body; throw error; } return body; }
async function tokenDoc(uid) { const snap = await db.doc(`${TOKEN_COLLECTION}/${uid}`).get(); return snap.exists ? snap.data() : null; }
async function setReauth(uid) { await db.doc(`usuarios/${uid}/integrations/googleCalendar`).set({ connected: true, syncStatus: "reauthorization_required", updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); }
async function getAccessToken(uid) {
  const stored = await tokenDoc(uid); if (!stored?.refreshTokenEncrypted) throw new HttpsError("failed-precondition", "GOOGLE_NOT_CONNECTED");
  const refreshToken = decrypt(stored.refreshTokenEncrypted);
  const params = new URLSearchParams({ client_id: secret(GOOGLE_CLIENT_ID, "GOOGLE_CLIENT_ID"), client_secret: secret(GOOGLE_CLIENT_SECRET, "GOOGLE_CLIENT_SECRET"), refresh_token: refreshToken, grant_type: "refresh_token" });
  const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: params });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) { if (body.error === "invalid_grant") { await setReauth(uid); throw new HttpsError("failed-precondition", "GOOGLE_REAUTH_REQUIRED"); } throw new HttpsError("unavailable", "Google Calendar no está disponible."); }
  return body.access_token;
}
async function callGoogle(uid, path, options = {}) { try { return await googleFetch(path, { ...options, headers: { authorization: `Bearer ${await getAccessToken(uid)}`, ...(options.headers || {}) } }); } catch (error) { if (error.status === 401) { await setReauth(uid); throw new HttpsError("failed-precondition", "GOOGLE_REAUTH_REQUIRED"); } throw error; } }
function audit(uid, action, details = {}) { return db.collection("auditoria").add({ accion: action, modulo: "Google Calendar", usuarioUid: uid, exito: details.exito !== false, detalles: { code: details.code || "" }, fecha: admin.firestore.FieldValue.serverTimestamp() }); }
function eventIdFor(appointmentId) { return crypto.createHash("sha256").update(`cognicion:${appointmentId}`).digest("hex").slice(0, 32); }
function appointmentEvent(appointment, uid) { const fecha = String(appointment.fecha || ""); const hora = String(appointment.hora || "09:00"); const minutes = Number(appointment.duracionMinutos || 60); const start = `${fecha}T${hora}:00`; const startDate = new Date(`${start}-06:00`); const end = new Date(startDate.getTime() + minutes * 60000); const privacy = appointment.calendarPrivacy || "generic"; const initials = String(appointment.pacienteNombre || "").split(/\s+/).filter(Boolean).map((x) => x[0]).join("").slice(0, 4); const summary = privacy === "initials" && initials ? initials : privacy === "name" && appointment.pacienteNombre ? appointment.pacienteNombre : appointment.tipo || "Consulta médica"; return { summary, description: "Cita gestionada en COGNICIÓN Labs. No contiene información clínica.", location: appointment.ubicacion || undefined, start: { dateTime: start, timeZone: TIME_ZONE }, end: { dateTime: end.toISOString(), timeZone: TIME_ZONE }, reminders: { useDefault: true }, extendedProperties: { private: { cognicionAppointmentId: appointment.id, cognicionOwnerUid: uid, cognicionSchemaVersion: "1" } } }; }
async function updateSync(uid, ref, patch) { await ref.set({ calendarSync: { ...(patch || {}), lastAttemptAt: admin.firestore.FieldValue.serverTimestamp() } }, { merge: true }); }

exports.googleOAuthStart = onCall({ secrets: [GOOGLE_CLIENT_ID, GOOGLE_OAUTH_REDIRECT_URI] }, async (request) => { const uid = requireAuth(request); const state = crypto.randomBytes(32).toString("base64url"); await db.doc(`_googleCalendarOAuthStates/${state}`).set({ uid, expiresAt: admin.firestore.Timestamp.fromMillis(Date.now() + STATE_TTL_MS) }); const query = new URLSearchParams({ client_id: secret(GOOGLE_CLIENT_ID, "GOOGLE_CLIENT_ID"), redirect_uri: redirectUri(), response_type: "code", access_type: "offline", prompt: "consent", include_granted_scopes: "true", scope: SCOPES.join(" "), state }); await audit(uid, "google_calendar_connection_started"); return { ok: true, authorizationUrl: `https://accounts.google.com/o/oauth2/v2/auth?${query}` }; });

exports.googleOAuthCallback = onRequest({ secrets: [GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_OAUTH_REDIRECT_URI, GOOGLE_TOKEN_ENCRYPTION_KEY] }, async (req, res) => { const state = String(req.query.state || ""); const code = String(req.query.code || ""); if (!state || !code) return res.status(400).send("Solicitud OAuth incompleta."); const stateRef = db.doc(`_googleCalendarOAuthStates/${state}`); const stateSnap = await stateRef.get(); const stateData = stateSnap.exists ? stateSnap.data() : null; await stateRef.delete().catch(() => {}); if (!stateData?.uid || !stateData.expiresAt || stateData.expiresAt.toMillis() < Date.now()) return res.status(400).send("Estado OAuth inválido o expirado."); const params = new URLSearchParams({ code, client_id: secret(GOOGLE_CLIENT_ID, "GOOGLE_CLIENT_ID"), client_secret: secret(GOOGLE_CLIENT_SECRET, "GOOGLE_CLIENT_SECRET"), redirect_uri: redirectUri(), grant_type: "authorization_code" }); const tokenResponse = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: params }); const tokens = await tokenResponse.json().catch(() => ({})); if (!tokenResponse.ok) return res.status(400).send("No fue posible completar la conexión con Google."); const uid = stateData.uid; const existing = await tokenDoc(uid); const refreshToken = tokens.refresh_token || (existing?.refreshTokenEncrypted ? decrypt(existing.refreshTokenEncrypted) : ""); if (!refreshToken) return res.status(400).send("Google no devolvió autorización offline; vuelve a intentarlo."); await db.doc(`${TOKEN_COLLECTION}/${uid}`).set({ refreshTokenEncrypted: encrypt(refreshToken), connectedAt: existing?.connectedAt || admin.firestore.FieldValue.serverTimestamp(), updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); const profile = await fetch("https://www.googleapis.com/oauth2/v3/userinfo", { headers: { authorization: `Bearer ${tokens.access_token}` } }).then((r) => r.json()).catch(() => ({})); await db.doc(`usuarios/${uid}/integrations/googleCalendar`).set({ connected: true, provider: "google", googleAccountEmail: String(profile.email || "Cuenta de Google"), scopes: Array.isArray(tokens.scope?.split(" ")) ? tokens.scope.split(" ") : SCOPES, syncStatus: "connected", updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); await audit(uid, "google_calendar_connection_completed"); return res.redirect(302, "/configuracion.html?googleCalendar=connected"); });

exports.googleCalendarStatus = onCall(async (request) => { const uid = requireAuth(request); const snap = await db.doc(`usuarios/${uid}/integrations/googleCalendar`).get(); if (!snap.exists) return { ok: true, connected: false, syncStatus: "disconnected" }; const data = snap.data(); return { ok: true, connected: data.connected === true, googleAccountEmail: data.googleAccountEmail || "", calendarId: data.calendarId || "", calendarSummary: data.calendarSummary || "", syncStatus: data.syncStatus || "connected", lastSuccessfulSyncAt: data.lastSuccessfulSyncAt || null }; });
exports.googleCalendarList = onCall(async (request) => { const uid = requireAuth(request); const data = await callGoogle(uid, "/users/me/calendarList?minAccessRole=writer&showDeleted=false"); return { ok: true, calendars: (data.items || []).map((item) => ({ id: item.id, summary: item.summary || item.summaryOverride || "Calendario", primary: item.primary === true, accessRole: item.accessRole })) }; });
exports.googleCalendarConnect = onCall(async (request) => { const uid = requireAuth(request); const calendarId = safeId(request.data?.calendarId, "Calendario"); const calendars = await callGoogle(uid, `/users/me/calendarList/${encodeURIComponent(calendarId)}`); if (!["writer", "owner", "freeBusyReader"].includes(calendars.accessRole) || calendars.accessRole === "freeBusyReader") throw new HttpsError("permission-denied", "El calendario no permite escribir."); await db.doc(`usuarios/${uid}/integrations/googleCalendar`).set({ connected: true, calendarId, calendarSummary: calendars.summary || calendars.summaryOverride || "Calendario", updatedAt: admin.firestore.FieldValue.serverTimestamp(), syncStatus: "connected" }, { merge: true }); await audit(uid, "google_calendar_selected"); return { ok: true, calendarId, calendarSummary: calendars.summary || calendars.summaryOverride || "Calendario" }; });

async function syncOne(uid, appointmentId, operation) { const ref = db.doc(`usuarios/${uid}/agenda/${appointmentId}`); const snap = await ref.get(); const appointment = snap.exists ? { id: snap.id, ...snap.data() } : null; const integrationSnap = await db.doc(`usuarios/${uid}/integrations/googleCalendar`).get(); const integration = integrationSnap.exists ? integrationSnap.data() : {}; if (!integration.connected) return { ok: true, skipped: true, code: "GOOGLE_NOT_CONNECTED" }; if (!integration.calendarId) throw new HttpsError("failed-precondition", "Selecciona un calendario de Google."); if (!appointment && operation !== "delete") throw new HttpsError("not-found", "Cita no encontrada."); const current = appointment?.calendarSync || {}; const eventId = current.googleEventId || eventIdFor(appointmentId); if (operation === "delete") { if (!current.googleEventId) return { ok: true, skipped: true }; try { await callGoogle(uid, `/calendars/${encodeURIComponent(integration.calendarId)}/events/${encodeURIComponent(current.googleEventId)}`, { method: "DELETE" }); } catch (error) { if (error.status !== 404) throw error; } return { ok: true, deleted: true }; } const event = appointmentEvent(appointment, uid); event.id = eventId; const method = current.googleEventId ? "PUT" : "POST"; const path = method === "PUT" ? `/calendars/${encodeURIComponent(integration.calendarId)}/events/${encodeURIComponent(eventId)}` : `/calendars/${encodeURIComponent(integration.calendarId)}/events`; let remote; try { remote = await callGoogle(uid, path, { method, body: JSON.stringify(event) }); } catch (error) { if (method === "POST" && (error.name === "AbortError" || error.code === "ETIMEDOUT")) { remote = await callGoogle(uid, `/calendars/${encodeURIComponent(integration.calendarId)}/events/${encodeURIComponent(eventId)}`); } else throw error; } await updateSync(uid, ref, { provider: "google", status: "synced", googleCalendarId: integration.calendarId, googleEventId: remote.id || eventId, googleEtag: remote.etag || null, lastSyncedAt: admin.firestore.FieldValue.serverTimestamp(), sourceUpdatedAt: admin.firestore.FieldValue.serverTimestamp(), errorCode: null, errorMessage: null }); return { ok: true, eventId: remote.id || eventId }; }
exports.calendarSyncAppointment = onCall(async (request) => { const uid = requireAuth(request); const appointmentId = safeId(request.data?.appointmentId, "Cita"); const operation = request.data?.operation === "delete" ? "delete" : "upsert"; const ref = db.doc(`usuarios/${uid}/agenda/${appointmentId}`); if (operation !== "delete" && !(await ref.get()).exists) throw new HttpsError("not-found", "Cita no encontrada."); try { const result = await syncOne(uid, appointmentId, operation); if (operation !== "delete") await audit(uid, "google_calendar_sync_succeeded"); return result; } catch (error) { const normalized = normalizeError(error); if (operation !== "delete" && (await ref.get()).exists) await updateSync(uid, ref, { provider: "google", status: "error", errorCode: normalized.code, errorMessage: normalized.userMessage, retryCount: admin.firestore.FieldValue.increment(1) }); await audit(uid, "google_calendar_sync_failed", { exito: false, code: normalized.code }); if (error instanceof HttpsError) throw error; throw new HttpsError(normalized.retryable ? "unavailable" : "failed-precondition", normalized.userMessage); } });
exports.googleCalendarSync = onCall(async (request) => { const uid = requireAuth(request); const snap = await db.collection(`usuarios/${uid}/agenda`).get(); let synced = 0; for (const doc of snap.docs) { try { await syncOne(uid, doc.id, "upsert"); synced += 1; } catch (error) { await updateSync(uid, doc.ref, { provider: "google", status: "error", errorCode: normalizeError(error).code, errorMessage: normalizeError(error).userMessage }); } } await db.doc(`usuarios/${uid}/integrations/googleCalendar`).set({ lastSuccessfulSyncAt: admin.firestore.FieldValue.serverTimestamp(), lastSyncAttemptAt: admin.firestore.FieldValue.serverTimestamp(), syncStatus: "connected" }, { merge: true }); return { ok: true, synced }; });
exports.googleCalendarDisconnect = onCall(async (request) => { const uid = requireAuth(request); const deleteRemoteEvents = request.data?.deleteRemoteEvents === true; const integrationRef = db.doc(`usuarios/${uid}/integrations/googleCalendar`); const integrationSnap = await integrationRef.get(); const integration = integrationSnap.exists ? integrationSnap.data() : {}; if (deleteRemoteEvents && integration.calendarId) { const appointments = await db.collection(`usuarios/${uid}/agenda`).get(); for (const item of appointments.docs) { const eventId = item.data()?.calendarSync?.googleEventId; if (eventId) await callGoogle(uid, `/calendars/${encodeURIComponent(integration.calendarId)}/events/${encodeURIComponent(eventId)}`, { method: "DELETE" }).catch(() => {}); } } await db.doc(`${TOKEN_COLLECTION}/${uid}`).delete(); await integrationRef.set({ connected: false, syncStatus: "disconnected", calendarId: admin.firestore.FieldValue.delete(), calendarSummary: admin.firestore.FieldValue.delete(), syncToken: admin.firestore.FieldValue.delete(), updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); await audit(uid, "google_calendar_disconnected"); return { ok: true }; });
exports.googleCalendarPullChanges = onCall(async (request) => { const uid = requireAuth(request); return { ok: true, prepared: true, direction: "pull", message: "La importación incremental queda preparada para la segunda etapa." }; });
exports.googleCalendarWebhook = onRequest(async (req, res) => { if (req.method !== "POST") return res.status(405).end(); const channelId = String(req.get("x-goog-channel-id") || ""); const resourceId = String(req.get("x-goog-resource-id") || ""); if (!channelId || !resourceId) return res.status(400).end(); console.info("Google Calendar webhook recibido", { channelId: channelId.slice(0, 12), resourceId: resourceId.slice(0, 12) }); return res.status(204).end(); });
