const LEGAL_VERSION = "2026-08-01";
const LEGAL_UPDATED_AT = "1 de agosto de 2026";

const privacyNotice = {
  type: "privacy_notice",
  title: "Aviso de Privacidad",
  version: LEGAL_VERSION,
  updatedAt: LEGAL_UPDATED_AT,
  sections: [
    ["AVISO DE PRIVACIDAD", "COGNICIÓN Labs\nVersión Beta"],
    ["1. Identidad del responsable", "COGNICIÓN Labs es una plataforma tecnológica desarrollada para apoyar la práctica clínica, la gestión de expedientes electrónicos, la investigación, la educación médica y el análisis de información en salud.\n\nEl responsable del tratamiento de los datos personales recabados mediante la plataforma es COGNICIÓN Labs, quien los tratará conforme a la legislación mexicana aplicable en materia de protección de datos personales."],
    ["2. Objeto del Aviso", "El presente Aviso de Privacidad tiene por objeto informar la forma en que COGNICIÓN Labs recopila, utiliza, almacena, protege y, en su caso, elimina los datos personales proporcionados por los usuarios durante el uso de la plataforma."],
    ["3. Datos personales que podrán recabarse", "Dependiendo del tipo de usuario y de las funciones utilizadas, podrán recabarse los siguientes datos:\n\nDatos de identificación:\n• Nombre completo.\n• Correo electrónico.\n• Fotografía de perfil, cuando sea proporcionada.\n• Institución de adscripción.\n• Especialidad médica.\n• Cargo o función profesional.\n\nDatos de autenticación:\n• Identificador de usuario.\n• Credenciales y métodos de autenticación.\n• Tokens y registros de sesión.\n\nDatos técnicos:\n• Dirección IP.\n• Navegador.\n• Sistema operativo.\n• Tipo de dispositivo.\n• Fecha y hora de acceso.\n• Registros de actividad.\n• Registros de errores y eventos de seguridad.\n\nDatos clínicos:\nCuando el usuario registre información de pacientes, la plataforma podrá almacenar datos de identificación del paciente, antecedentes, historia clínica, notas médicas, diagnósticos, tratamientos, estudios, escalas clínicas, evolución clínica, documentos anexos, imágenes clínicas e información de seguimiento."],
    ["4. Datos personales sensibles", "COGNICIÓN Labs podrá tratar datos personales sensibles relacionados con el estado de salud física y mental de los pacientes. Estos datos serán tratados exclusivamente para las finalidades relacionadas con la prestación, administración y apoyo de servicios clínicos, así como para actividades académicas, estadísticas o de investigación cuando corresponda y exista una base legal o autorización aplicable."],
    ["5. Finalidades del tratamiento", "Los datos personales podrán utilizarse para crear y administrar cuentas; verificar identidad y permisos; gestionar expedientes, notas, diagnósticos, tratamientos, estudios y documentos clínicos; aplicar escalas; generar reportes; permitir colaboración autorizada; corregir errores; mejorar estabilidad, funcionalidad y experiencia; fortalecer seguridad; detectar accesos no autorizados; mantener bitácoras de auditoría; generar estadísticas agregadas o anonimizadas; y desarrollar y evaluar nuevas funcionalidades.\n\nCOGNICIÓN Labs no venderá ni comercializará datos personales."],
    ["6. Inteligencia artificial", "COGNICIÓN Labs incorpora o podrá incorporar herramientas basadas en inteligencia artificial para organización de información clínica, borradores de notas, dictado y transcripción, búsqueda, apoyo documental, análisis estadístico, asistencia educativa y generación de hipótesis o sugerencias clínicas auxiliares. Estas herramientas son exclusivamente auxiliares. Sus resultados no constituyen por sí mismos diagnóstico, tratamiento o prescripción ni sustituyen el juicio clínico. El usuario deberá revisar, validar y aprobar toda información generada."],
    ["7. Responsabilidad del usuario respecto de los datos de pacientes", "El usuario declara que cuenta con autorización, consentimiento, atribución profesional o base legal correspondiente para registrar datos personales y datos personales sensibles de pacientes. Es responsable de utilizar la plataforma conforme a la legislación aplicable, normas éticas profesionales y políticas institucionales. COGNICIÓN Labs es una herramienta tecnológica de apoyo y no sustituye sus obligaciones legales, éticas y profesionales."],
    ["8. Seguridad de la información", "COGNICIÓN Labs implementa medidas técnicas, administrativas y organizativas orientadas a proteger la información, incluyendo autenticación, control de permisos por roles, restricción de acceso, cifrado de comunicaciones, bitácoras, control de sesiones, respaldos, monitoreo, detección de accesos no autorizados y reglas de seguridad en Firebase y Firestore. Ningún sistema informático puede garantizar seguridad absoluta."],
    ["9. Conservación de la información", "Los datos serán conservados durante el tiempo necesario para cumplir las finalidades descritas, mantener la continuidad de los servicios o atender obligaciones legales, clínicas, administrativas y de seguridad. Cuando corresponda, podrán ser eliminados, bloqueados, disociados o anonimizados. No se implementa eliminación automática de expedientes o información clínica como parte de este cambio."],
    ["10. Transferencias y proveedores tecnológicos", "COGNICIÓN Labs no venderá ni comercializará información personal. La información podrá ser tratada mediante proveedores tecnológicos necesarios para autenticación, almacenamiento, infraestructura en la nube, seguridad e inteligencia artificial, bajo medidas de seguridad y confidencialidad. También podrá comunicarse por obligación legal, solicitud de autoridad, protección de usuarios o plataforma, o autorización del titular o usuario correspondiente."],
    ["11. Derechos ARCO", "Los titulares podrán solicitar acceso, rectificación, cancelación u oposición conforme a la legislación aplicable. Mientras se implementa un módulo específico, las solicitudes podrán realizarse mediante aldo.sandokan@gmail.com. La solicitud deberá contener información suficiente para identificar al solicitante, describir los datos y señalar el derecho que desea ejercer."],
    ["12. Cambios al Aviso", "El Aviso podrá actualizarse conforme evolucione la plataforma, se incorporen funcionalidades o cambien las disposiciones legales. La versión vigente estará disponible dentro de la plataforma. Cuando el cambio sea sustancial, se solicitará nuevamente la aceptación."],
    ["13. Contacto", "COGNICIÓN Labs\nCorreo: aldo.sandokan@gmail.com\n© 2026 COGNICIÓN Labs"]
  ]
};

const betaConsent = {
  type: "beta_consent",
  title: "Consentimiento para uso de la plataforma Beta",
  version: LEGAL_VERSION,
  updatedAt: LEGAL_UPDATED_AT,
  sections: [["CONSENTIMIENTO PARA USO DE LA PLATAFORMA BETA", "COGNICIÓN Labs se encuentra actualmente en fase Beta. Durante esta etapa pueden existir funciones en desarrollo, cambios de interfaz, errores, interrupciones, modificaciones en los módulos o ajustes en la forma en que se almacenan y procesan determinados datos."], ["Al utilizar la plataforma, el usuario declara que:", "• Comprende que COGNICIÓN Labs se encuentra en fase de desarrollo y pruebas.\n• Comprende que algunas funciones pueden modificarse, actualizarse, suspenderse o presentar errores.\n• Se compromete a revisar y validar la información antes de utilizarla en la atención de pacientes.\n• Comprende que las herramientas de inteligencia artificial son auxiliares y no sustituyen su criterio profesional.\n• Se compromete a mantener la confidencialidad de sus credenciales.\n• Se compromete a no compartir su cuenta con otras personas.\n• Se compromete a utilizar únicamente información de pacientes respecto de la cual tenga autorización, atribución profesional o una base legal válida.\n• Comprende que la plataforma podrá generar bitácoras técnicas, clínicas y de seguridad.\n• Comprende que debe reportar errores importantes, accesos no autorizados o problemas de seguridad.\n• Reconoce que las funciones Beta no deben considerarse infalibles ni utilizarse sin supervisión profesional.\n• Acepta que COGNICIÓN Labs podrá actualizar las condiciones de uso cuando sea necesario."], ["Aclaración", "La aceptación de este consentimiento no autoriza usos distintos a los señalados en el Aviso de Privacidad y no implica la renuncia del usuario o de los titulares de los datos a los derechos reconocidos por la legislación aplicable."]]
};

const communicationsConsent = { type: "communications", title: "Comunicaciones de COGNICIÓN Labs", version: LEGAL_VERSION, updatedAt: LEGAL_UPDATED_AT };

export { LEGAL_VERSION, LEGAL_UPDATED_AT, privacyNotice, betaConsent, communicationsConsent };
