import bondParameters from "../data/bondParameters.json" with { type: "json" };
import angleParameters from "../data/angleParameters.json" with { type: "json" };
import torsionParameters from "../data/torsionParameters.json" with { type: "json" };
import nonbondedParameters from "../data/nonbondedParameters.json" with { type: "json" };
const pairKey=(a,b)=>[a,b].sort().join("|");
export function resolveAtomType(atomId,molecule,repository){const atom=molecule.getAtom(atomId),element=repository.get(atom.elementId),bonds=molecule.getBondsForAtom(atomId),orders=bonds.map(b=>b.order),degree=bonds.length;let atomType;if(element.id==="H"){const neighbor=degree?molecule.getAtom(bonds[0].atomAId===atomId?bonds[0].atomBId:bonds[0].atomAId):null;atomType=neighbor?.elementId==="C"?"H-C":neighbor?.elementId==="H"?"H":"H-hetero";}else if(element.id==="C")atomType=Math.max(...orders,0)>=3?"C-sp":Math.max(...orders,0)===2?"C-sp2":"C-sp3";else if(element.id==="N")atomType="N-neutral-trivalent";else if(element.id==="O"){const bondedToHydrogen=bonds.some(b=>molecule.getAtom(b.atomAId===atomId?b.atomBId:b.atomAId)?.elementId==="H");atomType=orders.includes(2)?"O-carbonyl":atom.formalCharge_e<0?"O-anionic":bondedToHydrogen?"O-hydroxyl":"O";}else atomType=["F","Cl","Br","I"].includes(element.id)?"halogen":element.id;const unresolved=["P","S"].includes(element.id),warnings=unresolved?[`${element.id}: tipo no parametrizado en Fase 3`]:[];return {atomId,atomType,confidence:unresolved?"unresolved":"limited",reasons:[`Elemento ${element.id}`,`vecinos ${degree}`,`órdenes ${orders.join(",")||"ninguno"}`],warnings,unresolved};}
export function resolveBondParameter(atomTypeA,atomTypeB,order){return bondParameters.find(p=>p.bondOrder===order&&pairKey(...p.atomTypes)===pairKey(atomTypeA,atomTypeB))??null;}
export function resolveAngleParameter(types){return angleParameters.find(p=>p.atomTypes.join("|")===types.join("|")||p.atomTypes.join("|")===types.slice().reverse().join("|"))??null;}
export function resolveTorsionParameter(types){return torsionParameters.find(p=>p.atomTypes.join("|")===types.join("|"))??null;}
export function resolveNonbondedParameter(atomType){return nonbondedParameters.find(p=>p.atomType===atomType)??null;}
