import * as THREE from "three";
import { createMolecularScene } from "./molecularScene.js";
import { createCameraController } from "./cameraController.js";
import { addLighting } from "./lightingController.js";
import { createRendererLifecycle } from "./rendererLifecycle.js";
import { createAtomMesh } from "./atomRenderer.js";
import { createBondMeshes } from "./bondRenderer.js";
import { atomWorldPosition } from "./molecularSceneAdapter.js";
import { createPicker } from "./molecularPicking.js";
import { createDragController } from "./dragController.js";
import { clearForceVectors, syncForceVectors } from "./forceVectorRenderer.js";
import { disposeObject3D } from "./resourceDisposer.js";
import { DEFAULT_RENDER_SETTINGS, RENDER_QUALITY, MAX_RENDERED_ATOMS_PHASE_4, MAX_RENDERED_BONDS_PHASE_4 } from "./renderSettings.js";
import { applySelection } from "./selectionRenderer.js";
import { getRendererDiagnostics, updateRendererDiagnostics } from "./rendererDiagnostics.js";

export function createMolecularRenderer({container,repository,onSelect,onMove,onStatus}) {
  const settings={...DEFAULT_RENDER_SETTINGS,...RENDER_QUALITY.medium};
  const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
  const sceneData=createMolecularScene(),cameraData=createCameraController(renderer.domElement),lighting=addLighting(sceneData.scene);
  const atomViews=new Map(),bondViews=new Map(); let selected=null,dragMode=false,molecule=null,disposed=false;
  renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,settings.maxPixelRatio)); container.replaceChildren(renderer.domElement);
  updateRendererDiagnostics({rendererInstances:getRendererDiagnostics().rendererInstances+1,initializationCount:getRendererDiagnostics().initializationCount+1,resizeObservers:1,eventListeners:10});
  const lifecycle=createRendererLifecycle(renderer,container,cameraData.camera,()=>{cameraData.controls.update();renderer.render(sceneData.scene,cameraData.camera);});
  const picker=createPicker(cameraData.camera,renderer.domElement);
  const clear=map=>{map.forEach(view=>disposeObject3D(view.mesh||view.group));map.clear();};
  const report=()=>updateRendererDiagnostics({sceneObjects:sceneData.scene.children.length,geometries:atomViews.size+bondViews.size,materials:atomViews.size+bondViews.size,atomVisuals:atomViews.size,bondVisuals:bondViews.size,forceVisuals:sceneData.forceGroup.children.length});
  const sync=(nextMolecule,forces=null)=>{if(disposed||!nextMolecule)return;molecule=nextMolecule;if(molecule.getAtoms().length>MAX_RENDERED_ATOMS_PHASE_4||molecule.getBonds().length>MAX_RENDERED_BONDS_PHASE_4){onStatus?.("Límite de visualización alcanzado; reduzca la molécula.");return;}const liveAtoms=new Set(molecule.getAtoms().map(a=>a.id));for(const [id,view] of atomViews)if(!liveAtoms.has(id)){sceneData.moleculeGroup.remove(view.mesh);disposeObject3D(view.mesh);atomViews.delete(id);}for(const atom of molecule.getAtoms()){const element=repository.get(atom.elementId);let view=atomViews.get(atom.id);if(!view){view=createAtomMesh(atom,element,settings);sceneData.moleculeGroup.add(view.mesh);atomViews.set(atom.id,view);}view.mesh.visible=settings.showHydrogens||atom.elementId!=="H";view.mesh.position.set(...Object.values(atomWorldPosition(atom)));view.mesh.userData.fixed=atom.fixed;}const liveBonds=new Set(molecule.getBonds().map(b=>b.id));for(const [id,view] of bondViews)if(!liveBonds.has(id)){sceneData.moleculeGroup.remove(view.group);disposeObject3D(view.group);bondViews.delete(id);}for(const bond of molecule.getBonds()){let view=bondViews.get(bond.id);if(!view){view=createBondMeshes(bond,settings);sceneData.moleculeGroup.add(view.group);bondViews.set(bond.id,view);}view.update(atomWorldPosition(molecule.getAtom(bond.atomAId)),atomWorldPosition(molecule.getAtom(bond.atomBId)));}if(settings.showForces)syncForceVectors(sceneData.forceGroup,molecule,forces,atomWorldPosition);else clearForceVectors(sceneData.forceGroup);report();lifecycle.requestRender();};
  const select=entity=>{if(selected?.mesh)applySelection(selected.mesh,false);selected=entity;const target=entity?.object;if(target?.userData.entityType==="atom"){const view=atomViews.get(target.userData.atomId);if(view)applySelection(view.mesh,true);onSelect?.({entityType:"atom",atomId:target.userData.atomId});}else if(target?.userData.entityType==="bond")onSelect?.({entityType:"bond",bondId:target.userData.bondId});else onSelect?.(null);lifecycle.requestRender();};
  const click=event=>{if(!dragMode){const objects=[...atomViews.values()].map(view=>view.mesh).concat([...bondViews.values()].map(view=>view.group));select(picker.pick(event,objects));}}; renderer.domElement.addEventListener("click",click);
  const drag=createDragController({camera:cameraData.camera,domElement:renderer.domElement,picker,getAtomMeshes:()=>[...atomViews.values()].map(v=>v.mesh),onSelect:id=>select({object:atomViews.get(id).mesh}),onMove:(id,position)=>{if(!dragMode)return;const atom=molecule?.getAtom(id);if(atom?.fixed){onStatus?.("El átomo está fijo.");return;}onMove?.(id,position);lifecycle.requestRender();}});
  const contextLost=event=>{event.preventDefault();lifecycle.stopContinuousRender("context-restore");onStatus?.("Contexto WebGL perdido.");}; const contextRestored=()=>{onStatus?.("Contexto WebGL restaurado.");if(molecule)sync(molecule);}; renderer.domElement.addEventListener("webglcontextlost",contextLost);renderer.domElement.addEventListener("webglcontextrestored",contextRestored);
  const captureViewportPng=({transparentBackground=false,includeGrid=true,includeAxes=true,includeLabels=true,includeForceVectors=true,filename="molecula.png"}={})=>{const old={grid:sceneData.grid.visible,forces:sceneData.forceGroup.visible,background:sceneData.scene.background};try{sceneData.grid.visible=includeGrid&&includeAxes;sceneData.forceGroup.visible=includeForceVectors;if(transparentBackground)sceneData.scene.background=null;renderer.render(sceneData.scene,cameraData.camera);return {dataUrl:renderer.domElement.toDataURL("image/png"),filename:String(filename).replace(/[^a-z0-9._-]/gi,"-").replace(/-+/g,"-")||"molecula.png"};}finally{sceneData.grid.visible=old.grid;sceneData.forceGroup.visible=old.forces;sceneData.scene.background=old.background;lifecycle.requestRender();}};
  return {sync,requestRender:lifecycle.requestRender,startContinuousRender:lifecycle.startContinuousRender,stopContinuousRender:lifecycle.stopContinuousRender,getLifecycleState:lifecycle.getState,fit:()=>{cameraData.fit(sceneData.moleculeGroup);lifecycle.requestRender();},resetCamera:()=>{cameraData.reset();lifecycle.requestRender();},setView:view=>{cameraData.setView(view);lifecycle.requestRender();},setDragMode:value=>{dragMode=value;cameraData.controls.enabled=!value;},setSettings:partial=>{Object.assign(settings,partial,RENDER_QUALITY[partial.quality]||{});lifecycle.requestRender();},capturePng:()=>captureViewportPng().dataUrl,captureViewportPng,setTheme:isLight=>{lighting.updateTheme(isLight);lifecycle.requestRender();},getMetrics:()=>({atoms:atomViews.size,bonds:bondViews.size,objects:sceneData.moleculeGroup.children.length,geometries:atomViews.size+bondViews.size,materials:atomViews.size+bondViews.size,instanced:false}),getDiagnostics:()=>getRendererDiagnostics(),getThreeRenderer:()=>renderer,dispose:()=>{if(disposed)return;disposed=true;renderer.domElement.removeEventListener("click",click);renderer.domElement.removeEventListener("webglcontextlost",contextLost);renderer.domElement.removeEventListener("webglcontextrestored",contextRestored);drag.dispose();clear(atomViews);clear(bondViews);clearForceVectors(sceneData.forceGroup);lifecycle.dispose();cameraData.dispose();renderer.dispose();renderer.domElement.remove();const prior=getRendererDiagnostics();updateRendererDiagnostics({rendererInstances:Math.max(0,prior.rendererInstances-1),resizeObservers:0,eventListeners:0,sceneObjects:0,geometries:0,materials:0,atomVisuals:0,bondVisuals:0,forceVisuals:0,disposalCount:prior.disposalCount+1});}};
}
